language: ruby
rvm:
  - 2.0.0
  - 2.1.0
gemfile:
  - gemfiles/rails-4.0.x.gemfile
before_install: gem install minitest -v "~> 4.7"
script: bundle exec rspec spec
notifications:
  email: false
  campfire:
    rooms:
      - secure: "Uhp18j/d6ZZ6pra2zgbEGrATV3bZgdbBCXKJg9/InjabOhM5EKc1+oaHd1xJ\nBrl6UY45kmVApoFuSnSvpxZs1YXJSNb5qqZrrHsQrw58OtHLJxlqRaYvHawD\nxzUKfdYkEErcrKuptZFEU5oYoXfEZ7hp26ucRy0JlguuN2Ql2AQ="
