language: ruby
env:
  global:
    - secure: N0x75qPPeUGUf/OhHalXpztEBTe8Bbw8sCRLStIGceq1d+QkIL62zKy1DUT7s3HJ5M0Zgz0/xLYzXcTVv1Z4qwK5rBEoalJcgtO/yJiK6Cs2VWoxZT480YLhIdB8F0cAR0ijOXHOOxordX8Ue5pblTnSGpV4DLks7aC3I0ubYJk=
    - JRUBY_OPTS=--2.0
rvm:
- 2.1.0
- 2.2.0
- jruby
gemfile:
- gemfiles/rails-4.1.x.gemfile
- gemfiles/rails-4.2.x.gemfile
before_install: rm -f Gemfile.lock
script: bundle exec rspec spec
notifications:
  email: false
  slack:
    secure: CGsNfCQllZJZFAgoEZcBZ5mITKSjMSSR8ht0v+iM1c6ElqaxoKxtI6Td6Ye2Aw/GgY5V4b3eDj439J9/0upbdxImTUc6aAXY2K5XjgKnk2TF7rrCDHT9gm9eBc6yHpWB3PTiuF0OLQnqheyPQ0wpkoC2Mt/F9tz0Rtk6OUzZYqA=
