language: ruby
rvm:
  - 1.9.2
  - 1.9.3
gemfile:
  - gemfiles/rails-3.2.x.gemfile
script: bundle exec rspec spec
notifications:
  email: false
  campfire:
    rooms:
      - secure: "dQZHlIcZl9dEXpoAcFMkozFD+v1ftbPYWvoqvuHL9PcPClUUCcedWZDikKSk\npdxmS7/LfA3VSPK1l+6Ky678/+PO3B0OH1xVBBLEiG617wFqHls5EGLWV7Tf\nHYjKjIOns6A16CnGTRHoJf8b7VTQYi+VQpLyX0t4OraS1h0+DJg="
